/**
 * Berean Standard Bible (BSB) Genesis 1–6, copied from `bibles/bsb/usfm/GEN.usfm` for Storybook and tests.
 * Text is public domain — see `bibles/bsb/ATTRIBUTION.md`.
 */
export const SAMPLE_BSB_GENESIS_USFM = `\\id GEN Autogenerated BSB by bsb2usfm

\\usfm 3.1
\\h Genesis
\\toc1 Genesis
\\toc2 Genesis
\\toc3 Gen
\\mt2 Genesis
\\mt1 
\\c 1
\\s1 The Creation
\\r (\\ref John 1:1–5|JHN 1:1-5\\ref*; \\ref Hebrews 11:1–3|HEB 11:1-3\\ref*)
\\p \\v 1 In the beginning God created the heavens and the earth.
\\p \\v 2 Now the earth was formless and void, and darkness was over the surface of the deep. And the Spirit of God was hovering over the surface of the waters.
\\s2 The First Day
\\pmo \\v 3 And God said, “Let there be light,”\\f + \\fr 1:3 \\ft Cited in \\ref 2 Corinthians 4:6|2CO 4:6\\ref*\\f* and there was light. \\v 4 And God saw that the light was good, and He separated the light from the darkness. \\v 5 God called the light “day,” and the darkness He called “night.”
\\pmo And there was evening, and there was morning — the first day.\\f + \\fr 1:5 \\ft Literally \\ft day one\\f*
\\s2 The Second Day
\\pmo \\v 6 And God said, “Let there be an expanse\\f + \\fr 1:6 \\ft Or \\fqa a canopy \\ft or \\fqa a firmament \\ft or \\fqa a vault\\ft ; also in verses 7, 8, 14, 15, 17, and 20\\f* between the waters, to separate the waters from the waters.” \\v 7 So God made the expanse and separated the waters beneath it from the waters above. And it was so. \\v 8 God called the expanse “sky.”
\\pmo And there was evening, and there was morning — the second day.
\\s2 The Third Day
\\pmo \\v 9 And God said, “Let the waters under the sky be gathered into one place, so that the dry land may appear.” And it was so. \\v 10 God called the dry land “earth,” and the gathering of waters He called “seas.” And God saw that it was good.
\\pmo \\v 11 Then God said, “Let the earth bring forth vegetation: seed-bearing plants and fruit trees, each bearing fruit with seed according to its kind.” And it was so. \\v 12 The earth produced vegetation: seed-bearing plants according to their kinds and trees bearing fruit with seed according to their kinds. And God saw that it was good.
\\pmo \\v 13 And there was evening, and there was morning — the third day.
\\s2 The Fourth Day
\\pmo \\v 14 And God said, “Let there be lights in the expanse of the sky to distinguish between the day and the night, and let them be signs to mark the seasons and days and years. \\v 15 And let them serve as lights in the expanse of the sky to shine upon the earth.” And it was so.
\\pmo \\v 16 God made two great lights: the greater light to rule the day and the lesser light to rule the night. And He made the stars as well.
\\pmo \\v 17 God set these lights in the expanse of the sky to shine upon the earth, \\v 18 to preside over the day and the night, and to separate the light from the darkness. And God saw that it was good.
\\pmo \\v 19 And there was evening, and there was morning — the fourth day.
\\s2 The Fifth Day
\\pmo \\v 20 And God said, “Let the waters teem with living creatures, and let birds fly above the earth in the open expanse of the sky.” \\v 21 So God created the great sea creatures and every living thing that moves, with which the waters teemed according to their kinds, and every winged bird after its kind. And God saw that it was good.
\\pmo \\v 22 Then God blessed them and said, “Be fruitful and multiply and fill the waters of the seas, and let birds multiply on the earth.”
\\pmo \\v 23 And there was evening, and there was morning — the fifth day.
\\s2 The Sixth Day
\\pmo \\v 24 And God said, “Let the earth bring forth living creatures according to their kinds: livestock, land crawlers, and beasts of the earth according to their kinds.” And it was so. \\v 25 God made the beasts of the earth according to their kinds, the livestock according to their kinds, and everything that crawls upon the earth according to its kind. And God saw that it was good.
\\pmo \\v 26 Then God said, “Let Us make man in Our image, after Our likeness, to rule over the fish of the sea and the birds of the air, over the livestock, and over all the earth itself\\f + \\fr 1:26 \\ft MT; Syriac \\fqa and over all the beasts of the earth\\f* and every creature that crawls upon it.”
\\b 
\\q1 \\v 27 So God created man in His own image;
\\q2 in the image of God He created him;
\\q2 male and female He created them.\\f + \\fr 1:27 \\ft Cited in \\ref Matthew 19:4|MAT 19:4\\ref* and Mark 10:6\\f*
\\pmo \\v 28 God blessed them and said to them, “Be fruitful and multiply, and fill the earth and subdue it; rule over the fish of the sea and the birds of the air and every creature that crawls upon the earth.”
\\pmo \\v 29 Then God said, “Behold, I have given you every seed-bearing plant on the face of all the earth, and every tree whose fruit contains seed. They will be yours for food. \\v 30 And to every beast of the earth and every bird of the air and every creature that crawls upon the earth — everything that has the breath of life in it — I have given every green plant for food.” And it was so.
\\pmo \\v 31 And God looked upon all that He had made, and indeed, it was very good.
\\pmo And there was evening, and there was morning — the sixth day.
\\c 2
\\s1 The Seventh Day
\\r (\\ref Exodus 16:22–30|EXO 16:22-30\\ref*; \\ref Hebrews 4:1–11|HEB 4:1-11\\ref*)
\\p \\v 1 Thus the heavens and the earth were completed in all their vast array. \\v 2 And by the seventh day God had finished the work He had been doing; so on that day He rested from all His work.\\f + \\fr 2:2 \\ft Cited in \\ref Hebrews 4:4|HEB 4:4\\ref*\\f*
\\p \\v 3 Then God blessed the seventh day and sanctified it, because on that day He rested from all the work of creation that He had accomplished.
\\s1 Man and Woman in the Garden
\\p \\v 4 This is the account of the heavens and the earth when they were created, in the day that the LORD\\f + \\fr 2:4 \\fqa LORD \\ft or \\fqa GOD\\ft , with capital letters, represents the proper name of the God of Israel and the one true God, transliterated from the Hebrew as \\fqa YHWH\\ft ; here and throughout the Scriptures.\\f* God made them.
\\p \\v 5 Now no shrub of the field had yet appeared on the earth, nor had any plant of the field sprouted, for the LORD God had not yet sent rain upon the earth, and there was no man to cultivate the ground. \\v 6 But springs\\f + \\fr 2:6 \\ft Or \\fqa mist\\f* welled up from the earth and watered the whole surface of the ground.
\\p \\v 7 Then the LORD God formed man from the dust of the ground and breathed the breath of life into his nostrils, and the man became a living being.\\f + \\fr 2:7 \\ft Or \\fqa a living soul\\ft ; cited in \\ref 1 Corinthians 15:45|1CO 15:45\\ref*\\f*
\\p \\v 8 And the LORD God planted a garden in Eden, in the east, where He placed the man He had formed. \\v 9 Out of the ground the LORD God gave growth to every tree that is pleasing to the eye and good for food. And in the middle of the garden were the tree of life and the tree of the knowledge of good and evil.
\\p \\v 10 A river flowed out of Eden to water the garden, and from there it branched into four headwaters:
\\b 
\\li1 \\v 11 The name of the first river is the Pishon; it winds through the whole land of Havilah, where there is gold. \\v 12 And the gold of that land is pure, and bdellium and onyx are found there.
\\li1 \\v 13 The name of the second river is the Gihon; it winds through the whole land of Cush.
\\li1 \\v 14 The name of the third river is the Tigris; it runs along the east side of Assyria.
\\li1 And the fourth river is the Euphrates.
\\p \\v 15 Then the LORD God took the man and placed him in the Garden of Eden to cultivate and keep it.
\\p \\v 16 And the LORD God commanded him, “You may eat freely from every tree of the garden, \\v 17 but you must not eat from the tree of the knowledge of good and evil; for in the day that you eat of it, you will surely die.”
\\p \\v 18 The LORD God also said, “It is not good for the man to be alone. I will make for him a suitable helper.”
\\p \\v 19 And out of the ground the LORD God formed every beast of the field and every bird of the air, and He brought them to the man to see what he would name each one. And whatever the man called each living creature, that was its name. \\v 20 The man gave names to all the livestock, to the birds of the air, and to every beast of the field. But for Adam\\f + \\fr 2:20 \\ft Or \\fqa the man\\ft , as in verses 19 and 21\\f* no suitable helper was found.
\\p \\v 21 So the LORD God caused the man to fall into a deep sleep, and while he slept, He took one of the man’s ribs\\f + \\fr 2:21 \\ft Or \\fqa took part of the man’s side\\ft ; similarly in verse 22\\f* and closed up the area with flesh. \\v 22 And from the rib that the LORD God had taken from the man, He made a woman and brought her to him. \\v 23 And the man said:
\\b 
\\q1 “This is now bone of my bones
\\q2 and flesh of my flesh;
\\q1 she shall be called ‘woman,’
\\q2 for out of man she was taken.”
\\p \\v 24 For this reason a man will leave his father and mother and be united to his wife, and they will become one flesh.\\f + \\fr 2:24 \\ft LXX \\fqa and the two will become one flesh\\ft ; cited in \\ref Matthew 19:5|MAT 19:5\\ref*, Mark 10:7–8, 1 Corinthians 6:16, and Ephesians 5:31\\f*
\\p \\v 25 And the man and his wife were both naked, and they were not ashamed.
\\c 3
\\s1 The Serpent’s Deception
\\r (\\ref Romans 5:12–21|ROM 5:12-21\\ref*)
\\p \\v 1 Now the serpent\\f + \\fr 3:1 \\ft Hebrew \\fqa nachash\\ft , translated in this chapter as \\fqa serpent\\ft , is translated in most cases as \\fqa snake\\ft .\\f* was more crafty than any beast of the field that the LORD God had made. And he said to the woman, “Did God really say, ‘You must not eat from any tree in the garden?’”
\\p \\v 2 The woman answered the serpent, “We may eat the fruit of the trees of the garden, \\v 3 but about the fruit of the tree in the middle of the garden, God has said, ‘You must not eat of it or touch it, or you will die.’”
\\p \\v 4 “You will not surely die,” the serpent told the woman. \\v 5 “For God knows that in the day you eat of it, your eyes will be opened and you will be like God, knowing good and evil.”
\\p \\v 6 When the woman saw that the tree was good for food and pleasing to the eyes, and that it was desirable for obtaining wisdom, she took the fruit and ate it. She also gave some to her husband who was with her, and he ate it.
\\p \\v 7 And the eyes of both of them were opened, and they knew that they were naked; so they sewed together fig leaves and made coverings for themselves.
\\s1 God Arraigns Adam and Eve
\\p \\v 8 Then the man and his wife heard the voice of the LORD God walking in the garden in the breeze\\f + \\fr 3:8 \\ft Or \\fqa at the breezy (time)\\ft ; Hebrew \\fqa unto the Ruach\\f* of the day, and they hid themselves from the presence of the LORD God among the trees of the garden.
\\p \\v 9 Then the LORD God called out to the man, “Where are you?”
\\p \\v 10 “I heard Your voice in the garden,” he replied, “and I was afraid because I was naked; so I hid myself.”
\\p \\v 11 “Who told you that you were naked?” asked the LORD God. “Have you eaten from the tree of which I commanded you not to eat?”
\\p \\v 12 And the man answered, “The woman whom You gave me, she gave me fruit from the tree, and I ate it.”
\\p \\v 13 Then the LORD God said to the woman, “What is this you have done?”
\\p “The serpent deceived me,” she replied, “and I ate.”
\\s1 The Fate of the Serpent
\\p \\v 14 So the LORD God said to the serpent:
\\b 
\\q1 “Because you have done this,
\\q2 cursed are you above all livestock
\\q2 and every beast of the field!
\\q1 On your belly will you go,
\\q2 and dust you will eat,
\\q2 all the days of your life.
\\q1 \\v 15 And I will put enmity between you and the woman,
\\q2 and between your seed and her seed.
\\q1 He will crush your head,
\\q2 and you will strike his heel.\\f + \\fr 3:15 \\ft Or \\fqa He will bruise your head, and you will bruise his heel\\ft . The same Hebrew root for \\fqa crush\\ft , \\fqa bruise\\ft , or \\fqa strike \\ft appears twice in this verse.\\f*”
\\s1 The Punishment of Mankind
\\p \\v 16 To the woman He said:
\\b 
\\q1 “I will sharply increase your pain in childbirth;
\\q2 in pain you will bring forth children.
\\q1 Your desire will be for your husband,\\f + \\fr 3:16 \\ft Or \\fqa You will desire to control your husband\\f*
\\q2 and he will rule over you.”
\\p \\v 17 And to Adam He said:
\\b 
\\q1 “Because you have listened to the voice of your wife
\\q2 and have eaten from the tree
\\q2 of which I commanded you not to eat,
\\q1 cursed is the ground because of you;
\\q2 through toil you will eat of it
\\q2 all the days of your life.
\\q1 \\v 18 Both thorns and thistles it will yield for you,
\\q2 and you will eat the plants of the field.
\\q1 \\v 19 By the sweat of your brow
\\q2 you will eat your bread,
\\q1 until you return to the ground —
\\q2 because out of it were you taken.
\\q1 For dust you are,
\\q2 and to dust you shall return.”
\\p \\v 20 And Adam named his wife Eve,\\f + \\fr 3:20 \\fqa Eve \\ft sounds like the Hebrew for \\fqa giving life \\ft or \\fqa living\\ft .\\f* because she would be the mother of all the living.
\\s1 The Expulsion from Paradise
\\p \\v 21 And the LORD God made garments of skin for Adam and his wife, and He clothed them.
\\p \\v 22 Then the LORD God said, “Behold, the man has become like one of Us, knowing good and evil. And now, lest he reach out his hand and take also from the tree of life, and eat, and live forever...”
\\p \\v 23 Therefore the LORD God banished him from the Garden of Eden to work the ground from which he had been taken. \\v 24 So He drove out the man and stationed cherubim on the east side of the Garden of Eden, along with a whirling sword of flame to guard the way to the tree of life.
\\c 4
\\s1 Cain and Abel
\\r (\\ref Hebrews 11:4|HEB 11:4\\ref*)
\\p \\v 1 And Adam had relations with his wife Eve, and she conceived and gave birth to Cain.\\f + \\fr 4:1 \\fqa Cain \\ft sounds like the Hebrew for \\fqa acquired \\ft or \\fqa brought forth\\ft .\\f*
\\p “With the help of the LORD I have brought forth a man,” she said.
\\p \\v 2 Later she gave birth to Cain’s brother Abel.
\\p Now Abel was a keeper of sheep, while Cain was a tiller of the soil. \\v 3 So in the course of time, Cain brought some of the fruit of the soil as an offering to the LORD, \\v 4 while Abel brought the best portions of the firstborn of his flock.
\\p And the LORD looked with favor on Abel and his offering, \\v 5 but He had no regard for Cain and his offering. So Cain became very angry, and his countenance fell.
\\p \\v 6 “Why are you angry,” said the LORD to Cain, “and why has your countenance fallen? \\v 7 If you do what is right, will you not be accepted? But if you refuse to do what is right, sin is crouching at your door; it desires you,\\f + \\fr 4:7 \\ft Or \\fqa it desires to control you\\f* but you must master it.”
\\p \\v 8 Then Cain said to his brother Abel, “Let us go out to the field.”\\f + \\fr 4:8 \\ft SP, LXX, Syriac, and Vulgate; Hebrew \\fqa Then Cain spoke to his brother Abel.\\f* And while they were in the field, Cain rose up against his brother Abel and killed him.
\\p \\v 9 And the LORD said to Cain, “Where is your brother Abel?”
\\p “I do not know!” he answered. “Am I my brother’s keeper?”
\\p \\v 10 “What have you done?” replied the LORD. “The voice of your brother’s blood cries out to Me from the ground. \\v 11 Now you are cursed and banished from the ground, which has opened its mouth to receive your brother’s blood from your hand. \\v 12 When you till the ground, it will no longer yield its produce to you. You will be a fugitive and a wanderer on the earth.”
\\p \\v 13 But Cain said to the LORD, “My punishment\\f + \\fr 4:13 \\ft Or \\fqa guilt \\ft or \\fqa sin\\f* is greater than I can bear. \\v 14 Behold, this day You have driven me from the face of the earth, and from Your face I will be hidden; I will be a fugitive and a wanderer on the earth, and whoever finds me will kill me.”
\\p \\v 15 “Not so!”\\f + \\fr 4:15 \\ft LXX, Vulgate, and Syriac; Hebrew \\fqa “Very well!” \\ft or \\fqa “Therefore:”\\f* replied the LORD. “If anyone slays Cain, then Cain will be avenged sevenfold.” And the LORD placed a mark on Cain, so that no one who found him would kill him.
\\p \\v 16 So Cain went out from the presence of the LORD and settled in the land of Nod,\\f + \\fr 4:16 \\fqa Nod \\ft means \\fqa wandering\\ft .\\f* east of Eden.
\\s1 The Descendants of Cain
\\p \\v 17 And Cain had relations with his wife, and she conceived and gave birth to Enoch. Then Cain built a city and named it after his son Enoch.
\\p \\v 18 Now to Enoch was born Irad, and Irad was the father of Mehujael, and Mehujael was the father of Methusael, and Methusael was the father of Lamech. \\v 19 And Lamech married two women, one named Adah and the other Zillah.
\\p \\v 20 Adah gave birth to Jabal; he was the father of those who dwell in tents and raise livestock. \\v 21 And his brother’s name was Jubal; he was the father of all who play the harp and flute.
\\p \\v 22 And Zillah gave birth to Tubal-cain, a forger of every implement of bronze and iron. And the sister of Tubal-cain was Naamah.
\\p \\v 23 Then Lamech said to his wives:
\\b 
\\q1 “Adah and Zillah, hear my voice;
\\q2 wives of Lamech, listen to my speech.
\\q1 For I have slain a man for wounding me,
\\q2 a young man for striking me.
\\q1 \\v 24 If Cain is avenged sevenfold,
\\q2 then Lamech seventy-sevenfold.”\\f + \\fr 4:24 \\ft Hebrew; LXX can be translated as either \\fqa seventy times seven \\ft or \\fqa seventy-sevenfold\\ft ; see also \\ref Matthew 18:22|MAT 18:22\\ref*.\\f*
\\s1 Seth and Enosh
\\p \\v 25 And Adam again had relations with his wife, and she gave birth to a son and named him Seth,\\f + \\fr 4:25 \\fqa Seth \\ft probably means \\fqa granted \\ft or \\fqa appointed\\ft .\\f* saying, “God has granted me another seed in place of Abel, since Cain killed him.”
\\p \\v 26 And to Seth also a son was born, and he called him Enosh.
\\p At that time men began to call upon\\f + \\fr 4:26 \\ft Or \\fqa to proclaim\\ft ; some translators \\fqa to invoke \\ft or \\fqa to call themselves by \\ft or \\fqa to profane \\ft \\f* the name of the LORD.
\\c 5
\\s1 The Descendants of Adam
\\r (\\ref 1 Chronicles 1:1–3|1CH 1:1-3\\ref*)
\\p \\v 1 This is the book of the generations of Adam. In the day that God created man, He made him in His own likeness. \\v 2 Male and female He created them,\\f + \\fr 5:2 \\ft Cited in \\ref Matthew 19:4|MAT 19:4\\ref* and Mark 10:6\\f* and He blessed them. And in the day they were created, He called them “man.”\\f + \\fr 5:2 \\ft Hebrew \\fqa Adam\\f*
\\p \\v 3 When Adam was 130 years old, he had a son in his own likeness, after his own image; and he named him Seth. \\v 4 And after he had become the father of Seth, Adam lived 800 years and had other sons and daughters. \\v 5 So Adam lived a total of 930 years, and then he died.
\\p \\v 6 When Seth was 105 years old, he became the father of Enosh. \\v 7 And after he had become the father of Enosh, Seth lived 807 years and had other sons and daughters. \\v 8 So Seth lived a total of 912 years, and then he died.
\\p \\v 9 When Enosh was 90 years old, he became the father of Kenan. \\v 10 And after he had become the father of Kenan, Enosh lived 815 years and had other sons and daughters. \\v 11 So Enosh lived a total of 905 years, and then he died.
\\p \\v 12 When Kenan was 70 years old, he became the father of Mahalalel. \\v 13 And after he had become the father of Mahalalel, Kenan lived 840 years and had other sons and daughters. \\v 14 So Kenan lived a total of 910 years, and then he died.
\\p \\v 15 When Mahalalel was 65 years old, he became the father of Jared. \\v 16 And after he had become the father of Jared, Mahalalel lived 830 years and had other sons and daughters. \\v 17 So Mahalalel lived a total of 895 years, and then he died.
\\s1 God Takes Up Enoch
\\r (\\ref Hebrews 11:5|HEB 11:5\\ref*)
\\p \\v 18 When Jared was 162 years old, he became the father of Enoch. \\v 19 And after he had become the father of Enoch, Jared lived 800 years and had other sons and daughters. \\v 20 So Jared lived a total of 962 years, and then he died.
\\p \\v 21 When Enoch was 65 years old, he became the father of Methuselah. \\v 22 And after he had become the father of Methuselah, Enoch walked with God\\f + \\fr 5:22 \\ft LXX \\fqa pleased God\\ft ; also in verse 24\\f* 300 years and had other sons and daughters. \\v 23 So Enoch lived a total of 365 years.
\\p \\v 24 Enoch walked with God, and then he was no more, because God had taken him away.\\f + \\fr 5:24 \\ft LXX \\fqa and he was not found, because God had taken him away\\ft ; cited in \\ref Hebrews 11:5|HEB 11:5\\ref*\\f*
\\s1 From Methuselah to Noah
\\p \\v 25 When Methuselah was 187 years old, he became the father of Lamech. \\v 26 And after he had become the father of Lamech, Methuselah lived 782 years and had other sons and daughters. \\v 27 So Methuselah lived a total of 969 years, and then he died.
\\p \\v 28 When Lamech was 182 years old, he had a son. \\v 29 And he named him Noah,\\f + \\fr 5:29 \\fqa Noah \\ft sounds like the Hebrew for \\fqa rest \\ft or \\fqa comfort\\ft .\\f* saying, “May this one comfort us in the labor and toil of our hands caused by the ground that the LORD has cursed.” \\v 30 And after he had become the father of Noah, Lamech lived 595 years and had other sons and daughters. \\v 31 So Lamech lived a total of 777 years, and then he died.
\\p \\v 32 After Noah was 500 years old, he became the father of Shem, Ham, and Japheth.
\\c 6
\\s1 Corruption on the Earth
\\r (\\ref Matthew 24:36–51|MAT 24:36-51\\ref*)
\\p \\v 1 Now when men began to multiply on the face of the earth and daughters were born to them, \\v 2 the sons of God saw that the daughters of men were beautiful, and they took as wives whomever they chose.
\\p \\v 3 So the LORD said, “My Spirit will not contend with man forever,\\f + \\fr 6:3 \\ft LXX and Syriac \\fqa My Spirit will not remain in man forever\\f* for he is mortal; his days shall be 120 years.”
\\p \\v 4 The Nephilim were on the earth in those days— and afterward as well— when the sons of God had relations with the daughters of men. And they bore them children who became the mighty men of old, men of renown.
\\p \\v 5 Then the LORD saw that the wickedness of man was great upon the earth, and that every inclination of the thoughts of his heart was altogether evil all the time. \\v 6 And the LORD regretted that He had made man on the earth, and He was grieved in His heart. \\v 7 So the LORD said, “I will blot out man, whom I have created, from the face of the earth — every man and beast and crawling creature and bird of the air — for I am grieved that I have made them.”
\\s1 Noah’s Favor with God
\\p \\v 8 Noah, however, found favor in the eyes of the LORD.
\\p \\v 9 This is the account of Noah. Noah was a righteous man, blameless in his generation; Noah walked with God. \\v 10 And Noah had three sons: Shem, Ham, and Japheth.
\\p \\v 11 Now the earth was corrupt in the sight of God, and full of violence. \\v 12 And God looked upon the earth and saw that it was corrupt; for all living creatures\\f + \\fr 6:12 \\ft Literally \\fqa all flesh\\ft ; similarly in verses 13, 17, and 19\\f* on the earth had corrupted their ways.
\\s1 Preparing the Ark
\\r (\\ref Hebrews 11:7|HEB 11:7\\ref*)
\\p \\v 13 Then God said to Noah, “The end of all living creatures has come before Me, because through them the earth is full of violence. Now behold, I will destroy both them and the earth.
\\p \\v 14 Make for yourself an ark of gopher wood;\\f + \\fr 6:14 \\fqa Gopher \\ft is an unknown kind of tree; possibly \\fqa cypress \\ft or \\fqa cedar\\ft .\\f* make rooms in the ark and coat it with pitch inside and out. \\v 15 And this is how you are to build it: The ark is to be 300 cubits long, 50 cubits wide, and 30 cubits high.\\f + \\fr 6:15 \\ft The ark was approximately 450 feet long, 75 feet wide, and 45 feet high (137.2 meters long, 22.9 meters wide, and 13.7 meters high).\\f* \\v 16 You are to make a roof\\f + \\fr 6:16 \\ft Or \\fqa skylight \\ft or \\fqa window\\f* for the ark, finish its walls a cubit from the top,\\f + \\fr 6:16 \\fqa A cubit \\ft is approximately 18 inches or 45.7 centimeters.\\f* place a door in the side of the ark, and build lower, middle, and upper decks.
\\p \\v 17 And behold, I will bring floodwaters upon the earth to destroy every creature under the heavens that has the breath of life. Everything on the earth will perish. \\v 18 But I will establish My covenant with you, and you will enter the ark — you and your sons and your wife and your sons’ wives with you.
\\p \\v 19 And you are to bring two of every living creature into the ark — male and female — to keep them alive with you. \\v 20 Two of every kind of bird and animal and crawling creature will come to you to be kept alive. \\v 21 You are also to take for yourself every kind of food that is eaten and gather it as food for yourselves and for the animals.”
\\p \\v 22 And Noah did everything precisely as God had commanded him.
`;

/** Short EXO snippet for multi-tab Storybook demos. */
export const SAMPLE_EXO_SNIPPET_USFM = `\\id EXO
\\c 1
\\p
\\v 1 These are the names of the sons of Israel who went to Egypt with Jacob, each with his family:
`;
