// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllowQuitAndExit() {
  return window['go']['main']['App']['AllowQuitAndExit']();
}

export function GetHostInfo() {
  return window['go']['main']['App']['GetHostInfo']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function ListRecentFolders() {
  return window['go']['main']['App']['ListRecentFolders']();
}

export function ListUsfmFiles(arg1) {
  return window['go']['main']['App']['ListUsfmFiles'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFilePickerHeader(arg1) {
  return window['go']['main']['App']['ReadFilePickerHeader'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SessionPath() {
  return window['go']['main']['App']['SessionPath']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
