// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';

export function GetHostInfo():Promise<main.HostInfo>;

export function ListRecentFolders():Promise<Array<session.RecentFolder>>;

export function ListUsfmFiles(arg1:string):Promise<Array<main.FileEntry>>;

export function LoadSettings():Promise<session.ApplicationSettings>;

export function OpenFolder(arg1:string):Promise<void>;

export function PickFolder():Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveSettings(arg1:session.ApplicationSettings):Promise<void>;

export function SessionPath():Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
