// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyChanges(arg1, arg2, arg3) {
  return window['go']['main']['UsfmService']['ApplyChanges'](arg1, arg2, arg3);
}

export function ClassifyDocument(arg1) {
  return window['go']['main']['UsfmService']['ClassifyDocument'](arg1);
}

export function ClassifyRange(arg1, arg2, arg3) {
  return window['go']['main']['UsfmService']['ClassifyRange'](arg1, arg2, arg3);
}

export function CloseDocument(arg1) {
  return window['go']['main']['UsfmService']['CloseDocument'](arg1);
}

export function GetCompletions(arg1, arg2, arg3) {
  return window['go']['main']['UsfmService']['GetCompletions'](arg1, arg2, arg3);
}

export function GetDiagnostics(arg1) {
  return window['go']['main']['UsfmService']['GetDiagnostics'](arg1);
}

export function GetStructure(arg1) {
  return window['go']['main']['UsfmService']['GetStructure'](arg1);
}

export function OpenDocument(arg1, arg2, arg3) {
  return window['go']['main']['UsfmService']['OpenDocument'](arg1, arg2, arg3);
}

export function RenderPreviewText(arg1, arg2) {
  return window['go']['main']['UsfmService']['RenderPreviewText'](arg1, arg2);
}
