// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {main} from '../models';

export function ApplyChanges(arg1:string,arg2:number,arg3:Array<engine.Change>):Promise<void>;

export function ClassifyDocument(arg1:string):Promise<main.TokensResult>;

export function ClassifyRange(arg1:string,arg2:number,arg3:number):Promise<main.TokensResult>;

export function CloseDocument(arg1:string):Promise<void>;

export function GetCompletions(arg1:string,arg2:number,arg3:number):Promise<Array<engine.CompletionItem>>;

export function GetDiagnostics(arg1:string):Promise<main.DiagnosticsResult>;

export function GetStructure(arg1:string):Promise<main.StructureResult>;

export function OpenDocument(arg1:string,arg2:number,arg3:string):Promise<void>;

export function RenderPreviewText(arg1:string,arg2:boolean):Promise<string>;
